//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/ShutDownHV.msg.
//

#ifndef _SHUTDOWNHV_M_H_
#define _SHUTDOWNHV_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "GenericAppMsg_m.h"
// }}



/**
 * Class generated from <tt>messages/ShutDownHV.msg</tt> by opp_msgc.
 * <pre>
 * packet ShutDownHV extends GenericAppMsg {
 *     string hvaddress;
 *     bool serverState;
 * }
 * </pre>
 */
class ShutDownHV : public ::GenericAppMsg
{
  protected:
    opp_string hvaddress_var;
    bool serverState_var;

  private:
    void copy(const ShutDownHV& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ShutDownHV&);

  public:
    ShutDownHV(const char *name=NULL, int kind=0);
    ShutDownHV(const ShutDownHV& other);
    virtual ~ShutDownHV();
    ShutDownHV& operator=(const ShutDownHV& other);
    virtual ShutDownHV *dup() const {return new ShutDownHV(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getHvaddress() const;
    virtual void setHvaddress(const char * hvaddress);
    virtual bool getServerState() const;
    virtual void setServerState(bool serverState);
};

inline void doPacking(cCommBuffer *b, ShutDownHV& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ShutDownHV& obj) {obj.parsimUnpack(b);}


#endif // _SHUTDOWNHV_M_H_
