//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/TTimer.msg.
//

#ifndef _TTIMER_M_H_
#define _TTIMER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "GenericAppMsg_m.h"
// }}



/**
 * Class generated from <tt>messages/TTimer.msg</tt> by opp_msgc.
 * <pre>
 * packet TTimer extends GenericAppMsg {
 *     
 * }
 * </pre>
 */
class TTimer : public ::GenericAppMsg
{
  protected:

  private:
    void copy(const TTimer& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TTimer&);

  public:
    TTimer(const char *name=NULL, int kind=0);
    TTimer(const TTimer& other);
    virtual ~TTimer();
    TTimer& operator=(const TTimer& other);
    virtual TTimer *dup() const {return new TTimer(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, TTimer& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TTimer& obj) {obj.parsimUnpack(b);}


#endif // _TTIMER_M_H_
